name: Parse JSON and Extract Answers

on:
  push:
    branches:
      - main  # Trigger action on push to the main branch
  pull_request:
    branches:
      - main  # Trigger action on pull request to the main branch

jobs:
  parse-json:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout the repository code

    - name: Set up Python
      uses: actions/setup-python@v4  # Set up Python environment
      with:
        python-version: '3.x'  # Use Python 3.x (latest version)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Ensure pip is up-to-date
        # Install any additional dependencies here (if required)

    - name: Run the Python script
      run: |
        python parse_json.py  # Run the Python script to parse the JSON and print answers

    - name: Display output
      run: |
        echo "Parsing completed successfully"  # Custom message after the script runs
